/**:
  ros_parameters:
    multi_agent: 3 # Maximum 3 if using GUI
    debug_rov: 0 # 0 or 1 for turning debug-mode off; 2 for ROV2, 3 for ROV3 and etc
    FOV_constraint: True
    radius_setp: 2.0
    distance_rovs: 2.0
    FOV_range_deg: 60.0
    FOV_range_soft_deg: 40.0
    cycle_time_publish: 0.05

